### ISSUE TITLE
getInitialShare is returning null in android,TypeError: Cannot read property 'getSharedText' of null at getInitialShare

### ISSUE THREAD

**Issue by rajafawady** [meedan/react-native-share-menu#262]
Error is cause by ShareMenu.getInitialShare(handleShare). Note that I am Using Javascript not typescript
This is my implementation:

import ShareMenu from 'react-native-share-menu';
const handleShare = useCallback((item) => {
    if (!item) {
      return;
    }

  }, []);

  useEffect(() => {
    const initializeShareMenu = async () => {
      ShareMenu.getInitialShare(handleShare);
    };

    initializeShareMenu();
  }, []);

  useEffect(() => {
    const listener = ShareMenu.addNewShareListener(handleShare);

    return () => {
      listener.remove();
    };
  }, []);

Here is the full error:

TypeError: Cannot read property 'getSharedText' of null
    at getInitialShare (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:197032:30)
    at ?anon_0_ (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:131191:56)
    at next (native)
    at asyncGeneratorStep (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:6076:26)
    at _next (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:6095:29)
    at anonymous (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:6100:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/3n472i6k/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:6092:25)
    at apply (native)
    at initializeShareMenu (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:131194:28)
    at anonymous (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:131197:26)
    at commitHookEffectListMount (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:96144:38)
    at commitPassiveMountOnFiber (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:97345:44)
    at commitPassiveMountEffects_complete (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:97317:40)
    at commitPassiveMountEffects_begin (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:97307:47)
    at commitPassiveMountEffects (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:97297:40)
    at flushPassiveEffectsImpl (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:98973:34)
    at flushPassiveEffects (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:98928:43)
    at performSyncWorkOnRoot (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:98218:28)
    at flushSyncCallbacks (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:87417:36)
    at flushSyncCallbacksOnlyInLegacyMode (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:87399:29)
    at scheduleUpdateOnFiber (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:97786:47)
    at updateContainer (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:100433:32)
    at render (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:100989:24)
    at renderElement (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:3212:77)
    at renderApplication (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:62933:27)
    at run (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:62272:42)
    at runApplication (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:62328:28)
    at apply (native)
    at __callFunction (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:3718:36)
    at anonymous (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:3438:31)
    at __guard (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:3655:15)
    at callFunctionReturnFlushedQueue (http://10.7.56.208:8081/index.bundle//&platform=android&dev=true&hot=false&lazy=true:3437:21)

**Comment by rajafawady** [comment]
k
